development:
  bucket: footballops-development
  access_key_id: AKIAJJS76LHBMMUAS25A
  secret_access_key: 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

test:
  bucket: footballops-test
  access_key_id: AKIAJJS76LHBMMUAS25A
  secret_access_key: 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

production:
  bucket: footballops-production
  access_key_id: AKIAJJS76LHBMMUAS25A
  secret_access_key: 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
